[music_comp_sorter]

db_path = "~/.local/share/music_comp_sorter/state.db"
metadata_cache_dir = "~/.local/share/music_comp_sorter/cache"
backup_dir = "~/music_comp_sorter_backups"

musicbrainz_rate_limit = 1.0
network_threads = 4
file_threads = 4

export_covers = true
fingerprint_enabled = true

acoustid_api_key = "fBJkLPMPQE"